//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trainline.TrainlineService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestEnvelope", Namespace="http://wsg.thetrainline.com/")]
    [System.SerializableAttribute()]
    public partial class RequestEnvelope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.AuthenticationHeader AuthenticationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.RequestBody RequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.AuthenticationHeader Authentication {
            get {
                return this.AuthenticationField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationField, value) != true)) {
                    this.AuthenticationField = value;
                    this.RaisePropertyChanged("Authentication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.RequestBody Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationHeader", Namespace="http://wsg.thetrainline.com/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UsernameAndPassword))]
    public partial class AuthenticationHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBody", Namespace="http://wsg.thetrainline.com/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.CustomerServiceRequestBody))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.AddAddressRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.GetSavedAddressesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateAddressRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.AddPaymentCardRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateSavedPaymentCardRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.DeleteSavedPaymentCardRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.GetSavedPaymentCardsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.RegisterCustomerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateCustomerProfileRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.ForgottenPasswordRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.PingRequest))]
    public partial class RequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsernameAndPassword", Namespace="http://wsg.thetrainline.com/")]
    [System.SerializableAttribute()]
    public partial class UsernameAndPassword : Trainline.TrainlineService.AuthenticationHeader {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerServiceRequestBody", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.AddAddressRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.GetSavedAddressesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateAddressRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.AddPaymentCardRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateSavedPaymentCardRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.DeleteSavedPaymentCardRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.GetSavedPaymentCardsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.RegisterCustomerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateCustomerProfileRequest))]
    public partial class CustomerServiceRequestBody : Trainline.TrainlineService.RequestBody {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.Credentials CustomerCredentialsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.Credentials CustomerCredentials {
            get {
                return this.CustomerCredentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCredentialsField, value) != true)) {
                    this.CustomerCredentialsField = value;
                    this.RaisePropertyChanged("CustomerCredentials");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddAddressRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class AddAddressRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.Address AddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSavedAddressesRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class GetSavedAddressesRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAddressRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class UpdateAddressRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.Address AddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddPaymentCardRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class AddPaymentCardRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
        
        private string AliasField;
        
        private string BillingAddressAliasField;
        
        private string CardholderNameField;
        
        private int ExpiryMonthField;
        
        private int ExpiryYearField;
        
        private bool IsDefaultField;
        
        private string PaymentCardNumberField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BillingAddressAlias {
            get {
                return this.BillingAddressAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddressAliasField, value) != true)) {
                    this.BillingAddressAliasField = value;
                    this.RaisePropertyChanged("BillingAddressAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardholderName {
            get {
                return this.CardholderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardholderNameField, value) != true)) {
                    this.CardholderNameField = value;
                    this.RaisePropertyChanged("CardholderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExpiryMonth {
            get {
                return this.ExpiryMonthField;
            }
            set {
                if ((this.ExpiryMonthField.Equals(value) != true)) {
                    this.ExpiryMonthField = value;
                    this.RaisePropertyChanged("ExpiryMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExpiryYear {
            get {
                return this.ExpiryYearField;
            }
            set {
                if ((this.ExpiryYearField.Equals(value) != true)) {
                    this.ExpiryYearField = value;
                    this.RaisePropertyChanged("ExpiryYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentCardNumber {
            get {
                return this.PaymentCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentCardNumberField, value) != true)) {
                    this.PaymentCardNumberField = value;
                    this.RaisePropertyChanged("PaymentCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateSavedPaymentCardRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class UpdateSavedPaymentCardRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
        
        private string AliasField;
        
        private string BillingAddressAliasField;
        
        private string CardholderNameField;
        
        private int ExpiryMonthField;
        
        private int ExpiryYearField;
        
        private bool IsDefaultField;
        
        private string NewAliasField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BillingAddressAlias {
            get {
                return this.BillingAddressAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddressAliasField, value) != true)) {
                    this.BillingAddressAliasField = value;
                    this.RaisePropertyChanged("BillingAddressAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardholderName {
            get {
                return this.CardholderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardholderNameField, value) != true)) {
                    this.CardholderNameField = value;
                    this.RaisePropertyChanged("CardholderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExpiryMonth {
            get {
                return this.ExpiryMonthField;
            }
            set {
                if ((this.ExpiryMonthField.Equals(value) != true)) {
                    this.ExpiryMonthField = value;
                    this.RaisePropertyChanged("ExpiryMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExpiryYear {
            get {
                return this.ExpiryYearField;
            }
            set {
                if ((this.ExpiryYearField.Equals(value) != true)) {
                    this.ExpiryYearField = value;
                    this.RaisePropertyChanged("ExpiryYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NewAlias {
            get {
                return this.NewAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.NewAliasField, value) != true)) {
                    this.NewAliasField = value;
                    this.RaisePropertyChanged("NewAlias");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteSavedPaymentCardRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class DeleteSavedPaymentCardRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
        
        private string AliasField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSavedPaymentCardsRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class GetSavedPaymentCardsRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterCustomerRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class RegisterCustomerRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorporateReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.DataProtectionActConcentIndicators DataProtectionActConcentIndicatorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DaytimePhoneNumberField;
        
        private string ForenameField;
        
        private Trainline.TrainlineService.Address HomeAddressField;
        
        private string SurnameField;
        
        private bool TermAndConditionsConsentIndicatorField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorporateReference {
            get {
                return this.CorporateReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CorporateReferenceField, value) != true)) {
                    this.CorporateReferenceField = value;
                    this.RaisePropertyChanged("CorporateReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.DataProtectionActConcentIndicators DataProtectionActConcentIndicators {
            get {
                return this.DataProtectionActConcentIndicatorsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataProtectionActConcentIndicatorsField, value) != true)) {
                    this.DataProtectionActConcentIndicatorsField = value;
                    this.RaisePropertyChanged("DataProtectionActConcentIndicators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DaytimePhoneNumber {
            get {
                return this.DaytimePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DaytimePhoneNumberField, value) != true)) {
                    this.DaytimePhoneNumberField = value;
                    this.RaisePropertyChanged("DaytimePhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Forename {
            get {
                return this.ForenameField;
            }
            set {
                if ((object.ReferenceEquals(this.ForenameField, value) != true)) {
                    this.ForenameField = value;
                    this.RaisePropertyChanged("Forename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Trainline.TrainlineService.Address HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool TermAndConditionsConsentIndicator {
            get {
                return this.TermAndConditionsConsentIndicatorField;
            }
            set {
                if ((this.TermAndConditionsConsentIndicatorField.Equals(value) != true)) {
                    this.TermAndConditionsConsentIndicatorField = value;
                    this.RaisePropertyChanged("TermAndConditionsConsentIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCustomerProfileRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class UpdateCustomerProfileRequest : Trainline.TrainlineService.CustomerServiceRequestBody {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorporateReferenceField;
        
        private Trainline.TrainlineService.DataProtectionActConcentIndicators DataProtectionActConcentIndicatorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DaytimePhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EveningPhoneNumberField;
        
        private string ForenameField;
        
        private Trainline.TrainlineService.Address HomeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewEmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewPasswordField;
        
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TermsAndConditionsConsentIndicatorField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorporateReference {
            get {
                return this.CorporateReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CorporateReferenceField, value) != true)) {
                    this.CorporateReferenceField = value;
                    this.RaisePropertyChanged("CorporateReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Trainline.TrainlineService.DataProtectionActConcentIndicators DataProtectionActConcentIndicators {
            get {
                return this.DataProtectionActConcentIndicatorsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataProtectionActConcentIndicatorsField, value) != true)) {
                    this.DataProtectionActConcentIndicatorsField = value;
                    this.RaisePropertyChanged("DataProtectionActConcentIndicators");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DaytimePhoneNumber {
            get {
                return this.DaytimePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DaytimePhoneNumberField, value) != true)) {
                    this.DaytimePhoneNumberField = value;
                    this.RaisePropertyChanged("DaytimePhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EveningPhoneNumber {
            get {
                return this.EveningPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EveningPhoneNumberField, value) != true)) {
                    this.EveningPhoneNumberField = value;
                    this.RaisePropertyChanged("EveningPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Forename {
            get {
                return this.ForenameField;
            }
            set {
                if ((object.ReferenceEquals(this.ForenameField, value) != true)) {
                    this.ForenameField = value;
                    this.RaisePropertyChanged("Forename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Trainline.TrainlineService.Address HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhoneNumber {
            get {
                return this.MobilePhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneNumberField, value) != true)) {
                    this.MobilePhoneNumberField = value;
                    this.RaisePropertyChanged("MobilePhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewEmailAddress {
            get {
                return this.NewEmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.NewEmailAddressField, value) != true)) {
                    this.NewEmailAddressField = value;
                    this.RaisePropertyChanged("NewEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword {
            get {
                return this.NewPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                    this.NewPasswordField = value;
                    this.RaisePropertyChanged("NewPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TermsAndConditionsConsentIndicator {
            get {
                return this.TermsAndConditionsConsentIndicatorField;
            }
            set {
                if ((this.TermsAndConditionsConsentIndicatorField.Equals(value) != true)) {
                    this.TermsAndConditionsConsentIndicatorField = value;
                    this.RaisePropertyChanged("TermsAndConditionsConsentIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForgottenPasswordRequest", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class ForgottenPasswordRequest : Trainline.TrainlineService.RequestBody {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingRequest", Namespace="http://schemas.datacontract.org/2004/07/WSG.CustomerService.Common.Contract.Test")]
    [System.SerializableAttribute()]
    public partial class PingRequest : Trainline.TrainlineService.RequestBody {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class Credentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailAddressField;
        
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AliasField;
        
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line5Field;
        
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Trainline.TrainlineService.AddressType> TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line4 {
            get {
                return this.Line4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line4Field, value) != true)) {
                    this.Line4Field = value;
                    this.RaisePropertyChanged("Line4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line5 {
            get {
                return this.Line5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line5Field, value) != true)) {
                    this.Line5Field = value;
                    this.RaisePropertyChanged("Line5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Trainline.TrainlineService.AddressType> Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    public enum AddressType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Billing = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivery = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Business = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataProtectionActConcentIndicators", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class DataProtectionActConcentIndicators : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DataProtectionAct1984ConsentIndicatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DataProtectionAct2003ConsentIndicatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DataProtectionAct1984ConsentIndicator {
            get {
                return this.DataProtectionAct1984ConsentIndicatorField;
            }
            set {
                if ((this.DataProtectionAct1984ConsentIndicatorField.Equals(value) != true)) {
                    this.DataProtectionAct1984ConsentIndicatorField = value;
                    this.RaisePropertyChanged("DataProtectionAct1984ConsentIndicator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DataProtectionAct2003ConsentIndicator {
            get {
                return this.DataProtectionAct2003ConsentIndicatorField;
            }
            set {
                if ((this.DataProtectionAct2003ConsentIndicatorField.Equals(value) != true)) {
                    this.DataProtectionAct2003ConsentIndicatorField = value;
                    this.RaisePropertyChanged("DataProtectionAct2003ConsentIndicator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://wsg.thetrainline.com/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.ErrorResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.AddAddressResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.GetSavedAddressesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateAddressResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.AddPaymentCardResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateSavedPaymentCardResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.DeleteSavedPaymentCardResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.GetSavedPaymentCardsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.ForgottenPasswordResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.RegisterCustomerResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.UpdateCustomerProfileResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trainline.TrainlineService.PingResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorResponse", Namespace="http://wsg.thetrainline.com/")]
    [System.SerializableAttribute()]
    public partial class ErrorResponse : Trainline.TrainlineService.Response {
        
        private Trainline.TrainlineService.Error[] ErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Trainline.TrainlineService.Error[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddAddressResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class AddAddressResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSavedAddressesResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class GetSavedAddressesResponse : Trainline.TrainlineService.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.Address[] AddressesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.Address[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAddressResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class UpdateAddressResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddPaymentCardResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class AddPaymentCardResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateSavedPaymentCardResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class UpdateSavedPaymentCardResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteSavedPaymentCardResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class DeleteSavedPaymentCardResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSavedPaymentCardsResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class GetSavedPaymentCardsResponse : Trainline.TrainlineService.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.Address[] BillingAddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trainline.TrainlineService.PaymentCard[] PaymentCardsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.Address[] BillingAddresses {
            get {
                return this.BillingAddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddressesField, value) != true)) {
                    this.BillingAddressesField = value;
                    this.RaisePropertyChanged("BillingAddresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trainline.TrainlineService.PaymentCard[] PaymentCards {
            get {
                return this.PaymentCardsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentCardsField, value) != true)) {
                    this.PaymentCardsField = value;
                    this.RaisePropertyChanged("PaymentCards");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForgottenPasswordResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class ForgottenPasswordResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterCustomerResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class RegisterCustomerResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCustomerProfileResponse", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class UpdateCustomerProfileResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingResponse", Namespace="http://schemas.datacontract.org/2004/07/WSG.CustomerService.Common.Contract.Test")]
    [System.SerializableAttribute()]
    public partial class PingResponse : Trainline.TrainlineService.Response {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://wsg.thetrainline.com/")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo {
            get {
                return this.AdditionalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfoField, value) != true)) {
                    this.AdditionalInfoField = value;
                    this.RaisePropertyChanged("AdditionalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentCard", Namespace="http://wsg.thetrainline.com/customerservice/v3.0/contract")]
    [System.SerializableAttribute()]
    public partial class PaymentCard : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AliasField;
        
        private string BillingAddressAliasField;
        
        private string CardholderNameField;
        
        private int ExpiryMonthField;
        
        private int ExpiryYearField;
        
        private bool IsDefaultField;
        
        private string PaymentCardNumberField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarningField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BillingAddressAlias {
            get {
                return this.BillingAddressAliasField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingAddressAliasField, value) != true)) {
                    this.BillingAddressAliasField = value;
                    this.RaisePropertyChanged("BillingAddressAlias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CardholderName {
            get {
                return this.CardholderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardholderNameField, value) != true)) {
                    this.CardholderNameField = value;
                    this.RaisePropertyChanged("CardholderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExpiryMonth {
            get {
                return this.ExpiryMonthField;
            }
            set {
                if ((this.ExpiryMonthField.Equals(value) != true)) {
                    this.ExpiryMonthField = value;
                    this.RaisePropertyChanged("ExpiryMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExpiryYear {
            get {
                return this.ExpiryYearField;
            }
            set {
                if ((this.ExpiryYearField.Equals(value) != true)) {
                    this.ExpiryYearField = value;
                    this.RaisePropertyChanged("ExpiryYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PaymentCardNumber {
            get {
                return this.PaymentCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentCardNumberField, value) != true)) {
                    this.PaymentCardNumberField = value;
                    this.RaisePropertyChanged("PaymentCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warning {
            get {
                return this.WarningField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningField, value) != true)) {
                    this.WarningField = value;
                    this.RaisePropertyChanged("Warning");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsg.thetrainline.com/", ConfigurationName="TrainlineService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsg.thetrainline.com/IService/Process", ReplyAction="http://wsg.thetrainline.com/IService/ProcessResponse")]
        Trainline.TrainlineService.Response Process(Trainline.TrainlineService.RequestEnvelope requestEnvelope);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsg.thetrainline.com/IService/Process", ReplyAction="http://wsg.thetrainline.com/IService/ProcessResponse")]
        System.Threading.Tasks.Task<Trainline.TrainlineService.Response> ProcessAsync(Trainline.TrainlineService.RequestEnvelope requestEnvelope);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Trainline.TrainlineService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Trainline.TrainlineService.IService>, Trainline.TrainlineService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trainline.TrainlineService.Response Process(Trainline.TrainlineService.RequestEnvelope requestEnvelope) {
            return base.Channel.Process(requestEnvelope);
        }
        
        public System.Threading.Tasks.Task<Trainline.TrainlineService.Response> ProcessAsync(Trainline.TrainlineService.RequestEnvelope requestEnvelope) {
            return base.Channel.ProcessAsync(requestEnvelope);
        }
    }
}
